### PR TITLE
Small performance boost for QMatrix computation

### PR DESCRIPTION
**Pull request by tlunet**
Hi Robert,

the original implementation of the QMatrix computation was suffering from 2 main downsides
1. each time _get_weights was called, it need to re-compute the same Barycentric interpolation polynomials that were already computed for the previous node => redundancy
2.  the use of quad is very expensive, and probably not needed since the integrand function is a polynomial of order M.

So I put the computation of the Barycentric polynomials directly in the _gen_QMatrix function, and changed the quad interpolation with an order M interpolation using Legendre nodes and weights. This does not change the dependencies of pySDC (nodes and weights come from scipy, quadrature use vectorized numpy operations). It improves a little bit the computation for large number of nodes (for M=100, requires only 6 sec. on my laptop, compared to 300 sec. for the previous version). From what I've compared, results are similar to machine precision (maybe if you have some regression test I could additionally check it).
Here is a comparison with the pythag package in terms of similarity, up to 150 nodes :

image

I did not remove the _get_weights method, since I'm not sure it is not used in an other function (did not modify it either ...).
So in case you're interested, feel free to take this merge request ;)

Best,
Thibaut

### CODE REVIEW

**Comment by pancetta** [comment]
Nice, thank you for the contribution. I'll get rid of the CI errors (which come from updated Python packages) and then merge it ASAP!

**Comment by pancetta** [comment]
OK, turns out I need the `_get_weights` function after all. Could you implement it with this function?

**Comment by pancetta** [comment]
You can run `nosetests -v pySDC/tests` to see what's going on. Takes about 30-40 minutes to complete.

**Comment by tlunet** [comment]
Done with #111 ... the nosetests gave me 3 errors and 2 fails due to packages that were not installed on my laptop (pestc4py, ...), but all the other went well. So I assume that the weight computation is not broken then ... ?

**Pull request merged**
