### PR TITLE
test_imexsweeper

### LINKED ISSUE #52: u_M is not u_end
Even for Gauss-Lobatto, a simple copy from u_M to u_end is not correct, if you are picky. To reproduce a RK/collocation scheme you will have to evaluate the collocation formula in ALL cases, not just for Gauss-Legendre et al.. Fix this e.g. here: 
https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/sweeper_classes/imex_1st_order.py#L146

Does this change anything...?

### PR DESCRIPTION
**Pull request by danielru**
Introduces a number of tests for the IMEX sweeper.
 - checks that matrix formulation of sweep is equivalent to node-to-node sweep
 - checks that update function matches node-to-node sweeps plus update (for Lobatto nodes, need to fix #52 to pass)
 - other tests making sure the IMEX sweeper does what is expected.

### CODE REVIEW

**Comment by danielru** [comment]
Fixes #43

**Comment by torbjoernk** [comment]
@pint-jenkins test this please

**Comment by torbjoernk** [comment]
@pint-jenkins test this please

**Comment by torbjoernk** [comment]
@pint-jenkins test this please

**Comment by torbjoernk** [comment]
@pint-jenkins test this please

**Comment by torbjoernk** [comment]
@pint-jenkins test this please

**Pull request merged**
