### PR TITLE
Bugfix for SE

### PR DESCRIPTION
**Pull request by lisawim**
I found some bug in the SE that I have fixed now (hopefully). I observed for some specific case that after jumping over the switch, the time step is not setting back to the initial dt in the switch estimator's post_step_processing function (only using SE in this specific case). The cause was the reset of the status variables. Before post_step_processing is reached, the status variables have already been reset to None. I assume that post_step_processing is already called after a successfully computed step, but status variables will be called after each step. For this reason, I moved switch_detected, t_switch back to the default dict, so that I can set it back to None after the next successful step. I also updated the hardcode references.

Probably @brownbaerchen has some idea for a cleaner alternative.

### CODE REVIEW

**Comment by lisawim** [comment]
I'm a bit confused about these several black errors.. Locally I hadn't any ones.

**Comment by pancetta** [comment]
> I'm a bit confused about these several black errors.. Locally I hadn't any ones.

Tried an update of black? Maybe a new version is unhappy about stuff old versions let through?

**Comment by lisawim** [comment]
As discussed with @brownbaerchen we did set the variables back to Status and did some adaptions in post_step_processing to make it work.

**Comment by lisawim** [comment]
Funny, my command line added the git add command to my commit..

**Comment by pancetta** [comment]
Welcome to the `git` jungle... you have 111 changes in this PR.

**Comment by brownbaerchen** [comment]
> Welcome to the `git` jungle... you have 111 changes in this PR.

Thanks to the black update, I guess......

**Comment by pancetta** [comment]
Merge `master` and you should be fine.

**Comment by lisawim** [comment]
You wrote I should do update my black. I did. I did blackening for 105 files, on Friday. Now you also did do this today. This is the reason why I have 111 files in this PR..

**Comment by brownbaerchen** [comment]
> Merge `master` and you should be fine.

We found that GitHub unfortunately doesn't update the reference in the past, right? As is the case already since Lisa did the same blackening as you. Did someone find a solution to this other than closing and reopening the PR?

**Comment by pancetta** [comment]
Worked!

**Comment by brownbaerchen** [comment]
> Worked!

Maybe we were doing some strange BS earlier then :D

**Pull request merged**
