### PR TITLE
Added a welcome message, but it's kind of stupid. Please suggest something more reasonable

### PR DESCRIPTION
**Pull request by brownbaerchen**
Looks like this now in the terminal: 
```
controller - INFO: Welcome to the one and only, really very astonishing and 87.3% bug free
                                 _____ _____   _____ 
                                / ____|  __ \ / ____|
                    _ __  _   _| (___ | |  | | |     
                   | '_ \| | | |\___ \| |  | | |     
                   | |_) | |_| |____) | |__| | |____ 
                   | .__/ \__, |_____/|_____/ \_____|
                   | |     __/ |                     
                   |_|    |___/                      
```

### CODE REVIEW

**Comment by tlunet** [comment]
:laughing: I wonder were the 87.3% comes from ...

**Comment by pancetta** [comment]
Any further ideas, concerns, complaints? If not (and if the CI thing is fixed now), I'll merge it.

**Comment by tlunet** [comment]
> Any further ideas, concerns, complaints? If not (and if the CI thing is fixed now), I'll merge it.

Not from me. I fully back up this humble welcome message !

**Comment by brownbaerchen** [comment]
One downside of this message is that I'll have to go and reduce the bug-free ratio every time I make a PR. :D

**Pull request merged**
