### PR TITLE
Some fixes for the new `numpy` 2.0 version.

### PR DESCRIPTION
**Pull request by brownbaerchen**
See #442 for details. Still need to fix the parallel SDC project.

### CODE REVIEW

**Comment by pancetta** [comment]
Weird.. it looks like the `parallelSDC` tests are stuck..

**Comment by brownbaerchen** [comment]
Was that why you limited the matplotlib version? Is it plotting something weird?

**Comment by pancetta** [comment]
I don't recall exactly what the problem was, but there was one. Maybe tests got stuck..? 🙄

**Comment by pancetta** [comment]
I have no clue what's going on with those three tests. Can someone reproduce this locally?

**Comment by brownbaerchen** [comment]
No works for me locally. Where are even the tests for python versions newer than 3.10? Did they pass? I didn't find them.

**Comment by pancetta** [comment]
Huh, good question! That's more than weird.

**Comment by tlunet** [comment]
I've added more adaptations to numpy2 in the [`qmat-switch`](https://github.com/tlunet/pySDC/tree/qmat-switch), the only problem left are for `parallelSDC` (test not passing).

In practice, removing the plotting function from the test make the test passe for 3 MPI threads, but not for 5 :
https://github.com/tlunet/pySDC/actions/runs/9625706930/job/26550873170#step:5:69

I suspect some additional multi-threading with the new versions of matplotlib (or numpy ...?) that make the mpirun execution reach a ressource limit that provoque the unending wait for the test

**Pull request closed without merging**
