### PR TITLE
Removed frozen class from problem class

### PR DESCRIPTION
**Pull request by brownbaerchen**
What do you think about the dump in the controller module? I am a bit unfamiliar with this and don't know how python version specific this is.

### CODE REVIEW

**Comment by tlunet** [comment]
Not the best idea to manipulate `__[...]__` attributes in Python. In this case, I think it should be better to write the dump directly as a method of the Problem class, with eventual overwriting of the base method in children classes

**Comment by tlunet** [comment]
PS : also, the `self.param = param` can be done at the end of the constructor, which avoid having to write `self.[...]` every time you have to manipulate it in the constructor. Also, it allows to put some parameter as property instead of attributes, if they can be determined with other attributes (for instance, dx and nX can be determined directly from the grid, ndim from the A matrix ...)

**Comment by brownbaerchen** [comment]
Honestly, because of the setup dump, I prefer the old way. Writing a function for the setup dump in every derived class is just annoying extra work.

Also, I don't get why you want the property functions. `N` determines the `A` matrix, not the other way around. And the problem domain is constant during a run, so why not compute `dx` only once in the beginning?
This can barely be generalised because it is just domain size / dof, but the domain size is problem specific.
Introducing abstraction for this also makes it more weird with ODEs. 

I will close this PR, because my version of what I think you want is bad. Maybe you can open a PR with how you would do it?

**Comment by tlunet** [comment]
Yeah, I understood a bit what you want to do, so I'll propose a tentative PR and then we'll maybe find the optimum approach. Let's keep this PR in the closet for now ;)

**Pull request closed without merging**
