### PR TITLE
Base collocation class on a more efficient/reliable barycentric interpolation

### PR DESCRIPTION
**Pull request by tlunet**
There you go, following #118 ...

### CODE REVIEW

**Comment by tlunet** [comment]
PS : a possible optimization would be to instantiate the LagrangeApproximation only once, once the node distribution on one level is fixed (and then, use the same for every block with the same node distribution, eventually with some scaling to take into account different intervals). Also, the CollBase class in core and the generic Collocation class could probably be merged, but that will be something for a more extensive rework of pySDC later, right ... ?

**Comment by pancetta** [comment]
Well done, well done! Thanks for your contribution, again!

Concerning optimization: (1) I'm not sure this is needed. In terms of performance, I doubt it. In terms of style, maybe yes, but hey.. (2) Yes, merging `Collbase` and `Collocation` absolutely makes sense, also because then the Python file is gone from `implementations`. Why wait for an extensive rework?

**Comment by tlunet** [comment]
Hum ... busyness and fear of the current structure of pySDC that requires plain collocation class for controllers arguments ? 

But I guess I can try to do something during my SBahn travel tomorrow ...

**Comment by tlunet** [comment]
Actually, I may have to correct some error first ...

**Comment by tlunet** [comment]
Guess you're good to go @pancetta :wink:

**Comment by pancetta** [comment]
Thanks a lot, this is really great work!

**Pull request merged**
