### PR TITLE
start using Travis

### PR DESCRIPTION
**Pull request by torbjoernk**
This seems to work fine now. Using Miniconda and not any of those Ubuntu or pip-installed packages as that didn't worked out that nicely due to broken blas/atlas/lapack libraries.

### CODE REVIEW

**Comment by torbjoernk** [comment]
Good to merge.

**Comment by pancetta** [comment]
Could you please fix the README.md? This is still pointing to Jenkins.

**Comment by torbjoernk** [comment]
@pancetta see here: http://stackoverflow.com/a/17624403. Unfortunately, not as convenient as with Jenkins.

**Comment by danielru** [comment]
Did this fix https://github.com/Parallel-in-Time/pySDC/issues/54?

**Pull request merged**
